project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Interfacial Electrochemical Engineering Lab"
  site-url: https://ChangLi.IEELab.github.io
  favicon: images/site-logo.jpg
  
  page-footer:
    left: |
      [Copyright © 2026 IEELab]
    right: |
      [Powered by IEELab]
    
  navbar: 
    title: "Interfacial Electrochemical Engineering Lab"
    search: false 

    right: 
      - text: "Home"
        href: index.qmd
      - text: "Team"
        href: Team.qmd
      - text: "Research"
        href: Research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Openings"
        href: Openings.qmd


format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细